export const results = [
    {
      _id: "1",
      name: "Red Dead Redemption 2",
      background_image: "https://image.api.playstation.com/cdn/UP1004/CUSA03041_00/Hpl5MtwQgOVF9vJqlfui6SDB5Jl4oBSq.png",
      genres: [{ id: 1, name: "Action" }, { id: 2, name: "Adventure" }],
      rating: 4.9,
      released: "2018-10-26",
    },
    {
      _id: "2",
      name: "The Witcher 3: Wild Hunt",
      background_image: "https://image.api.playstation.com/vulcan/ap/rnd/202211/0711/kh4MUIuMmHlktOHar3lVl6rY.png",
      genres: [{ id: 3, name: "RPG" }, { id: 2, name: "Adventure" }],
      rating: 4.8,
      released: "2015-05-19",
    },
  
    {
        _id: "3",
        name: "Assassin's Creed Valhalla",
        background_image: "https://image.api.playstation.com/vulcan/ap/rnd/202006/1520/EDtkdijFRwbmGKk1G9lrDoEF.png",
        genres: [{ id: 1, name: "Action" }, { id: 2, name: "Adventure" }],
        rating: 4.5,
        released: "2020-11-10",
    },
    {
        _id: "4",
        name: "Call of Duty: Warzone",
        background_image: "https://cdn.cloudflare.steamstatic.com/steam/apps/1962663/capsule_616x353.jpg?t=1701122618",
        genres: [{ id: 1, name: "Action" }, { id: 5, name: "Shooter" }],
        rating: 4.7,
        released: "2020-03-10",
    },
    {
        _id: "5",
        name: "Fortnite",
        background_image: "https://image.api.playstation.com/vulcan/ap/rnd/202311/0220/b2f6d383b0d49f69646e6f4231bfcb4d5255083b228d18b1.png",
        genres: [{ id: 5, name: "Shooter" }, { id: 6, name: "Survival" }],
        rating: 4.6,
        released: "2017-07-25",
    },
    {
        _id: "6",
        name: "Minecraft",
        background_image: "https://image.api.playstation.com/vulcan/img/cfn/11307x4B5WLoVoIUtdewG4uJ_YuDRTwBxQy0qP8ylgazLLc01PBxbsFG1pGOWmqhZsxnNkrU3GXbdXIowBAstzlrhtQ4LCI4.png",
        genres: [{ id: 6, name: "Survival" }, { id: 7, name: "Open World" }],
        rating: 4.4,
        released: "2011-11-18",
    },
    {
        _id: "7",
        name: "FIFA 22",
        background_image: "https://library.sportingnews.com/styles/facebook_1200x630/s3/2021-10/ea-fifa-22-cover-kylian-mbappe_1qeaco87s803l13iu0tnr84jhq.jpg?itok=B0Ysb2Rj",
        genres: [{ id: 8, name: "Sports" }],
        rating: 4.3,
        released: "2021-10-01",
    },
    {
        _id: "8",
        name: "Grand Theft Auto V",
        background_image: "https://image.api.playstation.com/vulcan/ap/rnd/202203/1409/oltI7Zc96usbdvhVVXcV1EAi.png",
        genres: [{ id: 1, name: "Action" }, { id: 2, name: "Adventure" }],
        rating: 4.9,
        released: "2013-09-17",
    },
    {
        _id: "9",
        name: "Among Us",
        background_image: "https://sm.ign.com/ign_in/cover/a/among-us/among-us_tkxm.jpg",
        genres: [{ id: 10, name: "Social Deduction" }],
        rating: 4.5,
        released: "2018-11-16",
    },
  ];